In [3]:
3 + 5 * 4


23

In [4]:
weight_kg = 60

In [6]:
weight_kg = 60.0
weight_kg_text = 'weight in kilograms:'
print(weight_kg)

60.0


In [7]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60.0


In [8]:
print('weight in pounds:', 2.2 * weight_kg)

weight in pounds: 132.0


In [9]:
print(weight_kg)

60.0


In [10]:
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 65.0


In [11]:
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, 'and in pounds:', weight_lb)


weight in kilograms: 65.0 and in pounds: 143.0


In [12]:
weight_kg = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)

weight in kilograms is now: 100.0 and weight in pounds is still: 143.0


In [15]:
mass = 47.5
mass * 2.0

95.0

In [17]:
age = 122
age - 20

102

In [68]:
mass = 47.5
age = 122
mass =2.0* mass
age = age -20

In [22]:
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)

Hopper Grace


In [23]:
import numpy

In [24]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [25]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [26]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [27]:
print(type(data))

<class 'numpy.ndarray'>


In [28]:
print(data.dtype)

float64


In [29]:
print(data.shape)

(60, 40)


In [30]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [31]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0


In [32]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [33]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [34]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [35]:
print(numpy.mean(data))

6.14875


In [36]:
import time
print(time.ctime())

Thu Jun 10 13:32:20 2021


In [37]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [38]:
patient_0 = data[0, :]
print('maximum inflammation for patient 0:', numpy.max(patient_0))

maximum inflammation for patient 0: 18.0


In [39]:
print('maximum inflammation for patient 2:', numpy.max(data[2, :]))

maximum inflammation for patient 2: 19.0


In [40]:
print(numpy.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [41]:
print(numpy.mean(data, axis=0).shape)

(40,)


In [42]:
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [43]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [44]:
print(element[:4])
print(element[4:])
print(element[:])

oxyg
en
oxygen


In [45]:
print(element[-1])
print(element[-2])

n
e


In [46]:
print(element[1:-1])

xyge


In [47]:
element = 'oxygen'
print('last three characters:', element[-3:])
element = 'carpentry'
print('last three characters:', element[-3:])
element = 'clone'
print('last three characters:', element[-3:])
element = 'hi'
print('last three characters:', element[-3:])

last three characters: gen
last three characters: try
last three characters: one
last three characters: hi


In [48]:
print(element[3:3])

In [49]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
D = numpy.delete(A, 1, 1)
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [52]:
D = numpy.delete(A, 1, 1)
print('D = ')
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [53]:
patient3_week1 = data[3, :7]
print(patient3_week1)

[0. 0. 2. 0. 4. 2. 2.]


In [54]:
numpy.diff(patient3_week1)

array([ 0.,  2., -2.,  4., -2.,  0.])

In [55]:
numpy.diff(axis)

NameError: name 'axis' is not defined

In [56]:
numpy.diff(axis=1)

TypeError: _diff_dispatcher() missing 1 required positional argument: 'a'

In [58]:
numpy.diff(data)

array([[ 0.,  1.,  2., ...,  1., -3.,  0.],
       [ 1.,  1., -1., ...,  0., -1.,  1.],
       [ 1.,  0.,  2., ...,  0., -1.,  0.],
       ...,
       [ 1.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  1., ..., -2.,  2., -2.],
       [ 0.,  1., -1., ..., -2.,  0., -1.]])

In [59]:
numpy.diff(data, axis=1)

array([[ 0.,  1.,  2., ...,  1., -3.,  0.],
       [ 1.,  1., -1., ...,  0., -1.,  1.],
       [ 1.,  0.,  2., ...,  0., -1.,  0.],
       ...,
       [ 1.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  1., ..., -2.,  2., -2.],
       [ 0.,  1., -1., ..., -2.,  0., -1.]])

In [60]:
diff(60, 40)

NameError: name 'diff' is not defined

In [61]:
numpy.diff(60, 40)

ValueError: diff requires input that is at least one dimensional

In [63]:
numpy.diff(60, 40)

ValueError: diff requires input that is at least one dimensional

In [65]:
numpy.diff(data, axis=1), axis=1)

SyntaxError: unmatched ')' (<ipython-input-65-3ccf54485135>, line 1)

In [66]:
numpy.max(numpy.diff(data, axis=1), axis=1)

array([ 7., 12., 11., 10., 11., 13., 10.,  8., 10., 10.,  7.,  7., 13.,
        7., 10., 10.,  8., 10.,  9., 10., 13.,  7., 12.,  9., 12., 11.,
       10., 10.,  7., 10., 11., 10.,  8., 11., 12., 10.,  9., 10., 13.,
       10.,  7.,  7., 10., 13., 12.,  8.,  8., 10., 10.,  9.,  8., 13.,
       10.,  7., 10.,  8., 12., 10.,  7., 12.])